<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FifthBox.ServerManager.Integrations.Certificates</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App\App.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Certes" Version="3.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.*" />
  </ItemGroup>

</Project>
