using System.Text;
using FifthBox.ServerManager.App.Routes;
using FifthBox.ServerManager.Shared.Routes;

namespace FifthBox.ServerManager.Integrations.ReverseProxy;

/// output is sorted so it's diffable and testable
public static class NginxConfigGenerator
{
    public static string Generate(
        IReadOnlyList<RouteConfig> routes,
        string acmeUpstream,
        IReadOnlyList<HostCertificate>? certificates = null,
        int httpsPort = ReverseProxyPorts.StandardHttps)
    {
        var certified = (certificates ?? [])
            .GroupBy(c => c.Hostname, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.Append("# Generated by FifthBox.ServerManager — do not edit by hand.\n");

        // resolve per request. a literal proxy_pass host resolves at load, so one stopped workload
        // would stop nginx starting and take every site down
        if (routes.Count > 0)
        {
            sb.Append("\nresolver 127.0.0.11 valid=10s ipv6=off;\n");

            // without this an uncertified hostname gets served someone else's cert
            // port 80 keeps its fallback so acme challenges still land
            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 443 ssl default_server;\n");
            sb.Append("    ssl_reject_handshake on;\n");
            sb.Append("}\n");
        }

        foreach (var host in routes.GroupBy(r => r.Hostname).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var certificate = certified.GetValueOrDefault(host.Key);

            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 80;\n");
            sb.Append($"    server_name {host.Key};\n");
            AppendAcmeLocation(sb, acmeUpstream);

            if (certificate is null)
            {
                AppendRouteLocations(sb, host);
                sb.Append("}\n");
                continue;
            }

            // https on = redirect. the ^~ challenge location above still wins, renewal needs port 80
            // spell out the port when it isn't 443 or the redirect lands on nothing
            sb.Append("    location / {\n");
            sb.Append($"        return 301 https://$host{ReverseProxyPorts.Suffix(httpsPort, https: true)}$request_uri;\n");
            sb.Append("    }\n");
            sb.Append("}\n");

            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 443 ssl;\n");
            sb.Append("    http2 on;\n");
            sb.Append($"    server_name {host.Key};\n");
            sb.Append($"    ssl_certificate {certificate.CertificatePath};\n");
            sb.Append($"    ssl_certificate_key {certificate.PrivateKeyPath};\n");
            sb.Append("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            sb.Append("    ssl_session_cache shared:SSL:10m;\n");
            AppendRouteLocations(sb, host);
            sb.Append("}\n");
        }

        return sb.ToString();
    }

    private static void AppendAcmeLocation(StringBuilder sb, string acmeUpstream)
    {
        // ^~ so basic auth can't gate the challenge
        // variable upstream so nginx still starts while the Host redeploys
        sb.Append("    location ^~ /.well-known/acme-challenge/ {\n");
        sb.Append($"        set $acme_upstream \"{acmeUpstream}\";\n");
        sb.Append("        proxy_pass http://$acme_upstream;\n");
        sb.Append("        proxy_set_header Host $host;\n");
        sb.Append("    }\n");
    }

    private static void AppendRouteLocations(StringBuilder sb, IGrouping<string, RouteConfig> host)
    {
        var upstreamIndex = 0;

        foreach (var route in host.OrderBy(r => r.Path, StringComparer.Ordinal))
        {
            var scheme = route.Scheme == UpstreamScheme.Https ? "https" : "http";
            sb.Append($"    location {route.Path} {{\n");

            // through a variable so a down upstream 502s instead of breaking startup
            var variable = $"upstream_{upstreamIndex++}";
            sb.Append($"        set ${variable} \"{route.UpstreamService}:{route.UpstreamPort}\";\n");
            sb.Append($"        proxy_pass {scheme}://${variable};\n");

            sb.Append("        proxy_set_header Host $host;\n");
            sb.Append("        proxy_set_header X-Real-IP $remote_addr;\n");
            sb.Append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
            sb.Append("        proxy_set_header X-Forwarded-Proto $scheme;\n");

            if (route.WebSockets)
            {
                sb.Append("        proxy_http_version 1.1;\n");
                sb.Append("        proxy_set_header Upgrade $http_upgrade;\n");
                sb.Append("        proxy_set_header Connection \"upgrade\";\n");
            }

            if (route.MaxBodySizeMb == 0)
            {
                // no buffering, or "unlimited" really means "as big as nginx's disk"
                sb.Append("        client_max_body_size 0;\n");
                sb.Append("        proxy_request_buffering off;\n");
            }
            else if (route.MaxBodySizeMb is { } mb)
            {
                sb.Append($"        client_max_body_size {mb}m;\n");
            }

            if (!string.IsNullOrEmpty(route.AuthFilePath))
            {
                sb.Append("        auth_basic \"Restricted\";\n");
                sb.Append($"        auth_basic_user_file {route.AuthFilePath};\n");
            }

            sb.Append("    }\n");
        }
    }
}
