using System.Text;
using FifthBox.ServerManager.App.Routes;
using FifthBox.ServerManager.Shared.Routes;

namespace FifthBox.ServerManager.Integrations.ReverseProxy;

/// Pure translation of routes into an nginx config — one <c>server</c> block per hostname, one
/// <c>location</c> per path, proxying to the workload's service name over the overlay. A hostname with
/// a certificate gets a second block on 443 and its port-80 block becomes a redirect.
/// Output is deterministic (sorted) so it's diffable and testable.
public static class NginxConfigGenerator
{
    public static string Generate(
        IReadOnlyList<RouteConfig> routes,
        string acmeUpstream,
        IReadOnlyList<HostCertificate>? certificates = null,
        int httpsPort = ReverseProxyPorts.StandardHttps)
    {
        var certified = (certificates ?? [])
            .GroupBy(c => c.Hostname, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.Append("# Generated by FifthBox.ServerManager — do not edit by hand.\n");

        // Every upstream resolves per-request. A literal proxy_pass host is resolved at config load, so
        // a workload that is stopped, scaled to zero or mid-redeploy would stop nginx starting at all —
        // taking every other site down with it. Docker's embedded DNS answers for container names and
        // forwards everything else.
        if (routes.Count > 0)
        {
            sb.Append("\nresolver 127.0.0.11 valid=10s ipv6=off;\n");

            // Without this, a hostname with no certificate of its own falls through to the first
            // `listen 443 ssl` block and is served someone else's certificate — a name mismatch the
            // visitor reads as a hijack. Rejecting the handshake fails it as what it is: not configured.
            // Port 80 keeps its fallback, so an ACME challenge still lands while a route is unapplied.
            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 443 ssl default_server;\n");
            sb.Append("    ssl_reject_handshake on;\n");
            sb.Append("}\n");
        }

        foreach (var host in routes.GroupBy(r => r.Hostname).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            var certificate = certified.GetValueOrDefault(host.Key);

            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 80;\n");
            sb.Append($"    server_name {host.Key};\n");
            AppendAcmeLocation(sb, acmeUpstream);

            if (certificate is null)
            {
                AppendRouteLocations(sb, host);
                sb.Append("}\n");
                continue;
            }

            // Enabling HTTPS *is* the redirect — there's no separate force-HTTPS switch. The challenge
            // location above stays on 80 and is matched with `^~`, so it wins over this: renewal
            // revalidates over port 80, and redirecting it would break issuance ~60 days later, when
            // nothing looks wrong.
            // The port has to be spelled out when it isn't 443, or the redirect lands on a port nothing
            // is listening on and every certified site becomes unreachable.
            sb.Append("    location / {\n");
            sb.Append($"        return 301 https://$host{ReverseProxyPorts.Suffix(httpsPort, https: true)}$request_uri;\n");
            sb.Append("    }\n");
            sb.Append("}\n");

            sb.Append('\n');
            sb.Append("server {\n");
            sb.Append("    listen 443 ssl;\n");
            sb.Append("    http2 on;\n");
            sb.Append($"    server_name {host.Key};\n");
            sb.Append($"    ssl_certificate {certificate.CertificatePath};\n");
            sb.Append($"    ssl_certificate_key {certificate.PrivateKeyPath};\n");
            sb.Append("    ssl_protocols TLSv1.2 TLSv1.3;\n");
            sb.Append("    ssl_session_cache shared:SSL:10m;\n");
            AppendRouteLocations(sb, host);
            sb.Append("}\n");
        }

        return sb.ToString();
    }

    private static void AppendAcmeLocation(StringBuilder sb, string acmeUpstream)
    {
        // `^~` beats every prefix location, so a basic-auth route can't gate the challenge. The
        // upstream goes through a variable for the same reason the route ones do: this is the Host
        // itself, and nginx must still start while it's redeploying.
        sb.Append("    location ^~ /.well-known/acme-challenge/ {\n");
        sb.Append($"        set $acme_upstream \"{acmeUpstream}\";\n");
        sb.Append("        proxy_pass http://$acme_upstream;\n");
        sb.Append("        proxy_set_header Host $host;\n");
        sb.Append("    }\n");
    }

    private static void AppendRouteLocations(StringBuilder sb, IGrouping<string, RouteConfig> host)
    {
        var upstreamIndex = 0;

        foreach (var route in host.OrderBy(r => r.Path, StringComparer.Ordinal))
        {
            var scheme = route.Scheme == UpstreamScheme.Https ? "https" : "http";
            sb.Append($"    location {route.Path} {{\n");

            // Going through a variable defers resolution to request time: an upstream that isn't
            // up 502s its own location instead of preventing nginx from starting.
            var variable = $"upstream_{upstreamIndex++}";
            sb.Append($"        set ${variable} \"{route.UpstreamService}:{route.UpstreamPort}\";\n");
            sb.Append($"        proxy_pass {scheme}://${variable};\n");

            sb.Append("        proxy_set_header Host $host;\n");
            sb.Append("        proxy_set_header X-Real-IP $remote_addr;\n");
            sb.Append("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
            sb.Append("        proxy_set_header X-Forwarded-Proto $scheme;\n");

            if (route.WebSockets)
            {
                sb.Append("        proxy_http_version 1.1;\n");
                sb.Append("        proxy_set_header Upgrade $http_upgrade;\n");
                sb.Append("        proxy_set_header Connection \"upgrade\";\n");
            }

            if (route.MaxBodySizeMb == 0)
            {
                // Buffering would spool the whole body to the edge's disk before the upstream sees a
                // byte, so "unlimited" would really mean "as big as nginx's disk".
                sb.Append("        client_max_body_size 0;\n");
                sb.Append("        proxy_request_buffering off;\n");
            }
            else if (route.MaxBodySizeMb is { } mb)
            {
                sb.Append($"        client_max_body_size {mb}m;\n");
            }

            if (!string.IsNullOrEmpty(route.AuthFilePath))
            {
                sb.Append("        auth_basic \"Restricted\";\n");
                sb.Append($"        auth_basic_user_file {route.AuthFilePath};\n");
            }

            sb.Append("    }\n");
        }
    }
}
