<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FifthBox.ServerManager.Client.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Client.Core\Client.Core.csproj" />
    <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
