using FifthBox.ServerManager.Shared.Routes;
using FifthBox.ServerManager.App.Routes;
using FifthBox.ServerManager.Integrations.ReverseProxy;

namespace FifthBox.ServerManager.Integrations.ReverseProxy.Tests;

[TestClass]
public class NginxConfigGeneratorTests
{
    private const string AcmeUpstream = "fbsm-host:8080";

    private static string Generate(IReadOnlyList<RouteConfig> routes) =>
        NginxConfigGenerator.Generate(routes, AcmeUpstream);

    private static string Generate(IReadOnlyList<RouteConfig> routes, params string[] certifiedHosts) =>
        NginxConfigGenerator.Generate(routes, AcmeUpstream, [.. certifiedHosts.Select(Certificate)]);

    private static HostCertificate Certificate(string hostname) => new()
    {
        Hostname = hostname,
        CertificatePath = $"/run/secrets/cert-{hostname}.pem",
        PrivateKeyPath = $"/run/secrets/key-{hostname}.pem",
    };

    private static RouteConfig Route(string host, string path, string service, int port) =>
        new() { Hostname = host, Path = path, UpstreamService = service, UpstreamPort = port };

    [TestMethod]
    public void Generates_a_server_block_with_proxy_pass()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)]);

        StringAssert.Contains(config, "server_name app.example.com;");
        StringAssert.Contains(config, "listen 80;");
        StringAssert.Contains(config, "location / {");
        StringAssert.Contains(config, "set $upstream_0 \"web:80\";");
        StringAssert.Contains(config, "proxy_pass http://$upstream_0;");
        StringAssert.Contains(config, "proxy_set_header Host $host;");
    }

    [TestMethod]
    public void Emits_websocket_upgrade_headers_when_enabled()
    {
        var config = Generate([
            new RouteConfig { Hostname = "ws.example.com", Path = "/", UpstreamService = "web", UpstreamPort = 80, WebSockets = true },
        ]);

        StringAssert.Contains(config, "proxy_http_version 1.1;");
        StringAssert.Contains(config, "proxy_set_header Upgrade $http_upgrade;");
        StringAssert.Contains(config, "proxy_set_header Connection \"upgrade\";");
    }

    [TestMethod]
    public void Emits_basic_auth_when_auth_file_present()
    {
        var config = Generate([
            new RouteConfig { Hostname = "secure.example.com", Path = "/", UpstreamService = "web", UpstreamPort = 80, AuthFilePath = "/etc/nginx/auth/r1.htpasswd" },
        ]);

        StringAssert.Contains(config, "auth_basic \"Restricted\";");
        StringAssert.Contains(config, "auth_basic_user_file /etc/nginx/auth/r1.htpasswd;");
    }

    [TestMethod]
    public void Omits_optional_directives_by_default()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)]);

        Assert.DoesNotContain("auth_basic", config);
        Assert.DoesNotContain("Upgrade", config);
    }

    [TestMethod]
    public void Groups_multiple_paths_under_one_server_block()
    {
        var config = Generate([
            Route("app.example.com", "/", "web", 80),
            Route("app.example.com", "/api", "api", 8080),
        ]);

        Assert.AreEqual(1, CountOccurrences(config, "server_name app.example.com;"));
        StringAssert.Contains(config, "location /api {");
        StringAssert.Contains(config, "set $upstream_1 \"api:8080\";");
    }

    [TestMethod]
    public void Separate_hosts_get_separate_server_blocks()
    {
        var config = Generate([
            Route("a.example.com", "/", "wa", 80),
            Route("b.example.com", "/", "wb", 80),
        ]);

        Assert.AreEqual(2, CountOccurrences(config, "server_name "));
    }

    [TestMethod]
    public void Output_is_deterministic_regardless_of_input_order()
    {
        var a = Generate([Route("b.example.com", "/", "wb", 80), Route("a.example.com", "/", "wa", 80)]);
        var b = Generate([Route("a.example.com", "/", "wa", 80), Route("b.example.com", "/", "wb", 80)]);

        Assert.AreEqual(a, b);
    }

    [TestMethod]
    public void No_routes_produces_header_only()
    {
        var config = Generate([]);

        StringAssert.Contains(config, "# Generated by FifthBox.ServerManager");
        Assert.DoesNotContain("server {", config);
    }

    [TestMethod]
    public void Every_server_block_serves_the_acme_challenge_path()
    {
        var config = Generate([
            Route("a.example.com", "/", "wa", 80),
            Route("b.example.com", "/", "wb", 80),
        ]);

        Assert.AreEqual(2, CountOccurrences(config, "location ^~ /.well-known/acme-challenge/ {"),
            "a hostname without the challenge location can never be issued a certificate");
        StringAssert.Contains(config, $"set $acme_upstream \"{AcmeUpstream}\";");
        StringAssert.Contains(config, "proxy_pass http://$acme_upstream;");
    }

    [TestMethod]
    public void The_acme_location_comes_before_the_route_locations()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)]);

        Assert.IsLessThan(
            config.IndexOf("location / {", StringComparison.Ordinal),
            config.IndexOf("location ^~ /.well-known/acme-challenge/ {", StringComparison.Ordinal));
    }

    [TestMethod]
    public void A_basic_auth_route_does_not_gate_the_acme_challenge()
    {
        var config = Generate([
            new RouteConfig
            {
                Hostname = "private.example.com", Path = "/", UpstreamService = "web", UpstreamPort = 80,
                AuthFilePath = "/etc/nginx/auth/private",
            },
        ]);

        // `^~` wins over the prefix location, so the challenge is reachable without credentials —
        // otherwise issuance 401s on exactly the sites that most want a certificate.
        StringAssert.Contains(config, "location ^~ /.well-known/acme-challenge/ {");
        var acme = config.IndexOf("location ^~ /.well-known/acme-challenge/ {", StringComparison.Ordinal);
        var auth = config.IndexOf("auth_basic", StringComparison.Ordinal);
        Assert.IsLessThan(auth, acme);
    }

    [TestMethod]
    public void The_acme_upstream_is_configurable()
    {
        var config = NginxConfigGenerator.Generate([Route("app.example.com", "/", "web", 80)], "edge-host:9000");

        StringAssert.Contains(config, "set $acme_upstream \"edge-host:9000\";");
    }

    [TestMethod]
    public void A_certified_hostname_gets_a_tls_block_serving_its_routes()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)], "app.example.com");

        StringAssert.Contains(config, "listen 443 ssl;");
        StringAssert.Contains(config, "ssl_certificate /run/secrets/cert-app.example.com.pem;");
        StringAssert.Contains(config, "ssl_certificate_key /run/secrets/key-app.example.com.pem;");
        Assert.IsLessThan(
            config.IndexOf("set $upstream_0", StringComparison.Ordinal),
            config.IndexOf("listen 443 ssl;", StringComparison.Ordinal),
            "the routes move to the TLS block");
    }

    [TestMethod]
    public void A_certified_hostname_redirects_port_80()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)], "app.example.com");

        StringAssert.Contains(config, "return 301 https://$host$request_uri;");
        Assert.AreEqual(1, CountOccurrences(config, "set $upstream_0"),
            "the port-80 block redirects rather than proxying, so the upstream appears once");
    }

    [TestMethod]
    public void An_uncertified_hostname_is_refused_rather_than_handed_another_sites_certificate()
    {
        // detroitlakestkd sorts first, so without a default server it is what every uncertified
        // hostname on the box gets offered — a name mismatch the visitor reads as a hijack.
        var config = NginxConfigGenerator.Generate(
            [Route("detroitlakestkd.com", "/", "a", 80), Route("digikeygolf.com", "/", "b", 80)],
            AcmeUpstream,
            [Certificate("detroitlakestkd.com")]);

        StringAssert.Contains(config, "listen 443 ssl default_server;");
        StringAssert.Contains(config, "ssl_reject_handshake on;");
        Assert.IsLessThan(
            config.IndexOf("server_name detroitlakestkd.com", StringComparison.Ordinal),
            config.IndexOf("default_server", StringComparison.Ordinal),
            "the default server has to precede the certified blocks to be the fallback");
    }

    [TestMethod]
    public void Port_80_keeps_its_fallback_so_a_challenge_lands_while_a_route_is_unapplied()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)], "app.example.com");

        Assert.AreEqual(0, CountOccurrences(config, "listen 80 default_server"));
    }

    [TestMethod]
    public void The_redirect_carries_a_non_standard_https_port()
    {
        var config = NginxConfigGenerator.Generate(
            [Route("app.example.com", "/", "web", 80)], AcmeUpstream, [Certificate("app.example.com")], httpsPort: 8443);

        // Without the port the redirect lands on 443, where nothing is listening — every certified site
        // would become unreachable the moment HTTPS was enabled.
        StringAssert.Contains(config, "return 301 https://$host:8443$request_uri;");
    }

    [TestMethod]
    public void The_redirect_omits_the_port_when_it_is_standard()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)], "app.example.com");

        StringAssert.Contains(config, "return 301 https://$host$request_uri;");
    }

    [TestMethod]
    public void The_redirect_never_covers_the_acme_challenge()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)], "app.example.com");

        // Renewal revalidates over port 80 every time. Redirecting the challenge would break issuance
        // ~60 days later, long after anyone would connect it to enabling HTTPS.
        var port80 = config[config.IndexOf("listen 80;", StringComparison.Ordinal)..config.IndexOf("listen 443 ssl;", StringComparison.Ordinal)];
        StringAssert.Contains(port80, "location ^~ /.well-known/acme-challenge/ {");
        Assert.IsLessThan(
            port80.IndexOf("return 301", StringComparison.Ordinal),
            port80.IndexOf("location ^~ /.well-known/acme-challenge/ {", StringComparison.Ordinal));
    }

    [TestMethod]
    public void A_hostname_without_a_certificate_stays_on_port_80()
    {
        var config = Generate([
            Route("plain.example.com", "/", "web", 80),
            Route("secure.example.com", "/", "web", 80),
        ], "secure.example.com");

        // nginx refuses to start when an ssl_certificate file is missing, so a hostname whose key the
        // edge isn't carrying must not get an ssl_certificate line — one bad host would take the whole
        // edge down, every other site with it.
        Assert.AreEqual(1, CountOccurrences(config, "listen 443 ssl;"));
        Assert.AreEqual(1, CountOccurrences(config, "ssl_certificate "));
        Assert.DoesNotContain("cert-plain.example.com", config);

        var plain = ServerBlock(config, "plain.example.com");
        StringAssert.Contains(plain, "set $upstream_0", "it still proxies on 80");
        Assert.DoesNotContain("return 301", plain, "an uncertified hostname has nowhere to redirect to");
    }

    [TestMethod]
    public void A_certificate_for_a_hostname_with_no_routes_emits_nothing()
    {
        var config = NginxConfigGenerator.Generate([], AcmeUpstream, [Certificate("ghost.example.com")]);

        Assert.DoesNotContain("server {", config);
    }

    /// The one server block naming this hostname, up to its closing brace at column 0.
    private static string ServerBlock(string config, string hostname)
    {
        var start = config.LastIndexOf("server {", config.IndexOf($"server_name {hostname};", StringComparison.Ordinal), StringComparison.Ordinal);
        var end = config.IndexOf("\n}\n", start, StringComparison.Ordinal);
        return config[start..end];
    }

    private static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var i = 0;
        while ((i = haystack.IndexOf(needle, i, StringComparison.Ordinal)) >= 0)
        {
            count++;
            i += needle.Length;
        }

        return count;
    }

    [TestMethod]
    public void External_upstreams_resolve_at_request_time_not_config_load()
    {
        var config = Generate([
            new RouteConfig
            {
                Hostname = "nas.example.com", Path = "/", UpstreamService = "nas.lan", UpstreamPort = 5000
            },
        ]);

        // A literal proxy_pass host is resolved when nginx starts; one bad name would stop the whole
        // edge coming up. Going through a variable defers it, so a bad host 502s just that location.
        StringAssert.Contains(config, "resolver 127.0.0.11");
        StringAssert.Contains(config, "set $upstream_0 \"nas.lan:5000\";");
        StringAssert.Contains(config, "proxy_pass http://$upstream_0;");
    }

    [TestMethod]
    public void A_workload_upstream_also_defers_so_a_stopped_service_cannot_stop_nginx()
    {
        var config = Generate([
            new RouteConfig { Hostname = "app.example.com", Path = "/", UpstreamService = "web", UpstreamPort = 80 },
        ]);

        // A swarm service has no DNS entry while it is stopped, scaled to zero or mid-redeploy. Resolving
        // it literally at config load would make nginx refuse to start and take every other site down.
        StringAssert.Contains(config, "resolver 127.0.0.11");
        StringAssert.Contains(config, "set $upstream_0 \"web:80\";");
        StringAssert.Contains(config, "proxy_pass http://$upstream_0;");
    }

    [TestMethod]
    public void No_body_size_leaves_the_nginx_default()
    {
        var config = Generate([Route("app.example.com", "/", "web", 80)]);

        Assert.DoesNotContain("client_max_body_size", config);
        Assert.DoesNotContain("proxy_request_buffering", config);
    }

    [TestMethod]
    public void Zero_body_size_is_unlimited_and_streams_to_the_upstream()
    {
        var config = Generate([Route("registry.example.com", "/", "registry", 5000) with { MaxBodySizeMb = 0 }]);

        StringAssert.Contains(config, "client_max_body_size 0;");
        StringAssert.Contains(config, "proxy_request_buffering off;");
    }

    [TestMethod]
    public void A_body_size_caps_in_megabytes_and_keeps_buffering()
    {
        var config = Generate([Route("upload.example.com", "/", "web", 80) with { MaxBodySizeMb = 50 }]);

        StringAssert.Contains(config, "client_max_body_size 50m;");
        Assert.DoesNotContain("proxy_request_buffering", config);
    }

    [TestMethod]
    public void Body_size_is_scoped_to_its_own_location()
    {
        var config = Generate([
            Route("app.example.com", "/", "web", 80),
            Route("app.example.com", "/upload", "uploads", 8080) with { MaxBodySizeMb = 0 },
        ]);

        var root = config.IndexOf("location / {", StringComparison.Ordinal);
        var upload = config.IndexOf("location /upload {", StringComparison.Ordinal);
        var limit = config.IndexOf("client_max_body_size", StringComparison.Ordinal);

        Assert.IsTrue(root < upload && upload < limit, "the limit belongs to /upload, not /");
    }

    [TestMethod]
    public void No_routes_means_no_resolver_directive()
    {
        Assert.DoesNotContain("resolver", Generate([]));
    }

    [TestMethod]
    public void Https_upstream_uses_the_https_scheme()
    {
        var config = Generate([
            new RouteConfig
            {
                Hostname = "secure.example.com", Path = "/", UpstreamService = "10.0.0.9", UpstreamPort = 8443,
                Scheme = UpstreamScheme.Https,
            },
        ]);

        StringAssert.Contains(config, "proxy_pass https://$upstream_0;");
    }

    [TestMethod]
    public void Two_external_locations_on_one_host_get_distinct_variables()
    {
        var config = Generate([
            new RouteConfig { Hostname = "h.example.com", Path = "/a", UpstreamService = "a.lan", UpstreamPort = 1,},
            new RouteConfig { Hostname = "h.example.com", Path = "/b", UpstreamService = "b.lan", UpstreamPort = 2,},
        ]);

        StringAssert.Contains(config, "set $upstream_0 \"a.lan:1\";");
        StringAssert.Contains(config, "set $upstream_1 \"b.lan:2\";");
    }
}
